version: 2.1

orbs:
  gcp-cli: circleci/gcp-cli@1.8.3

executors:
  default:
    docker:
      - image: google/cloud-sdk
    working_directory: go/src/github.com/manakuro/golang-deploy-gcp

jobs:
  build:
    executor:
      name: default
    steps:
      - checkout
      - setup_remote_docker:
          version: 18.06.0-ce
      - gcp-cli/initialize
      - gcp-cli/install
      - run:
          command: |
            gcloud --quiet auth configure-docker
            echo "done"

workflows:
  deploy_gcr:
    jobs:
      - build
