version: 2.1

orbs:
  gcp-cli: circleci/gcp-cli@1.8.3

executors:
  default:
    docker:
      - image: google/cloud-sdk
    working_directory: go/src/github.com/manakuro/golang-deploy-gcp

jobs:
  build:
    executor:
      name: default
    steps:
      - checkout
      - setup_remote_docker:
          version: 18.06.0-ce
      - gcp-cli/initialize
      - gcp-cli/install
      - run:
          name: Push image to GCR
          command: |
            gcloud --quiet auth configure-docker
            
            docker build -t golang-deploy-gcp .

            today=$(date "+%Y%m%d%H%M%S")
            TAG=gcr.io/golang-deploy-gcp/golang-deploy-gcp:pushed-${today}
            docker tag golang-deploy-gcp $TAG
            docker push $TAG

            LATEST_TAG=gcr.io/golang-deploy-gcp/golang-deploy-gcp:latest
            docker tag golang-deploy-gcp $LATEST_TAG
            docker push $LATEST_TAG

workflows:
  deploy_gcr:
    jobs:
      - build
